#include "../include/rockpaperscissors.h"
#include "../include/utils.h"

void menu(void){
    // Game menu
    printf(CYN"\t\t\t\t1.Rock 🪨\n"reset);
    printf(CYN"\t\t\t\t2.Scissors ✂️\n"reset);
    printf(CYN"\t\t\t\t3.Paper 📄\n"reset);
    printf(CYN"\t\t\t\t4.Scorecard 💯\n"reset);
    printf(CYN"\t\t\t\t5.Exit ⚠️\n"reset);
}

int menuChoice(){
    // Choice from the user
    printf(GRN "Enter your choice: "reset);
    scanf("%hd",&choice);
    return choice;
}

int computerChoice(){
    srand(time(NULL)); 
    //Choice generated by computer
	opponent = 1 + rand() % 3;
    return opponent;
}

void exitAnimation() {
    printf(RED "\n\t\t\t\tExiting");
    fflush(stdout);

    int i;
    for (i = 0; i < 5; ++i) {
        usleep(100000);  // Adjust the delay as needed
        printf("..");
        fflush(stdout);
    }
    printf("👋\n\n"reset);
}

void printHeader(){
printf("______           _     ______                       _____      _                \n");        
printf("| ___ \\         | |    | ___ \\                     /  ___|    (_)                \n");     
printf("| |_/ /___   ___| | __ | |_/ /_ _ _ __   ___ _ __  \\ `--.  ___ _ ___ ___  ___  _ __ ___\n"); 
printf("|    // _ \\ / __| |/ / |  __/ _` | '_ \\ / _ \\ '__|  `--. \\/ __| / __/ __|/ _ \\| '__/ __|    \n");
printf("| |\\ \\ (_) | (__|   <  | | | (_| | |_) |  __/ |    /\\__/ / (__| \\__ \\__ \\ (_) | |  \\__ \\    \n");
printf("\\_| \\_\\___/ \\___|_|\\_\\ \\_|  \\__,_| .__/ \\___|_|    \\____/ \\___|_|___/___/\\___/|_|  |___/    \n");
printf("                                 | |                                                    \n");
printf("                                 |_|                                                    \n");
printf("\t\t\t\t\tMade by ❤️ lila (Rocky)");
}
